module AMEE
  
  class Airports
    
    def self.airports
      [
        ["United Kingdom, Aberdeen [ABZ]", "ABZ"],
        ["United Kingdom, Barra [BRR]", "BRR"],
        ["United Kingdom, Belfast [BFS]", "BFS"],
        ["United Kingdom, Benbecula [BEB]", "BEB"],
        ["United Kingdom, Birmingham [BHX]", "BHX"],
        ["United Kingdom, Bournemouth [BOH]", "BOH"],
        ["United Kingdom, Bristol [BRS]", "BRS"],
        ["United Kingdom, Cardiff (Wales) [CWL]", "CWL"],
        ["United Kingdom, Dundee (Scotland) [DND]", "DND"],
        ["United Kingdom, East Midlands [EMA]", "EMA"],
        ["United Kingdom, Edinburgh (Scotland) [EDI]", "EDI"],
        ["United Kingdom, Exeter [EXT]", "EXT"],
        ["United Kingdom, Gibraltar [GIB]", "GIB"],
        ["United Kingdom, Glasgow [GLA]", "GLA"],
        ["United Kingdom, Guernsey [GCI]", "GCI"],
        ["United Kingdom, Inverness (Scotland) [INV]", "INV"],
        ["United Kingdom, Islay (Scotland) [ILY]", "ILY"],
        ["United Kingdom, Isle of Man [IOM]", "IOM"],
        ["United Kingdom, Isles of Scilly [ISC]", "ISC"],
        ["United Kingdom, Jersey [JER]", "JER"],
        ["United Kingdom, Kirkwall (Scotland) [KOI]", "KOI"],
        ["United Kingdom, Leeds [LBA]", "LBA"],
        ["United Kingdom, Lerwick (Scotland) [LWK]", "LWK"],
        ["United Kingdom, Liverpool [LPL]", "LPL"],
        ["United Kingdom, London (City) [LCY]", "LCY"],
        ["United Kingdom, London (Gatwick) [LGW]", "LGW"],
        ["United Kingdom, London (Heathrow) [LHR]", "LHR"],
        ["United Kingdom, London (Luton) [LTN]", "LTN"],
        ["United Kingdom, London (Stansted) [STN]", "STN"],
        ["United Kingdom, Manchester [MAN]", "MAN"],
        ["United Kingdom, Newcastle [NCL]", "NCL"],
        ["United Kingdom, Newquay [NQY]", "NQY"],
        ["United Kingdom, Out Skerries (Scotland) [OUK]", "OUK"],
        ["United Kingdom, Southampton [SOU]", "SOU"],
        ["United Kingdom, Stornoway (Scotland) [SYY]", "SYY"],
        ["United Kingdom, Sumburgh (Scotland) [LSI]", "LSI"],
        ["United Kingdom, Teesside [MME]", "MME"],
        ["United Kingdom, Wick (Scotland) [WIC]", "WIC"],
        ["---", "---"],
        ["Afghanistan, Kabul [KBL]", "KBL"],
        ["Albania, Tirane [TIA]", "TIA"],
        ["Algeria, Algiers [ALG]", "ALG"],
        ["American Samoa, Pago Pago [PPG]", "PPG"],
        ["Angola, Luanda [LAD]", "LAD"],
        ["Antigua and Barbuda, Saint John's [ANU]", "ANU"],
        ["Argentina, Buenos Aires [EZE]", "EZE"],
        ["Armenia, Yerevan [EVN]", "EVN"],
        ["Australia, Adelaide [ADL]", "ADL"],
        ["Australia, Brisbane [BNE]", "BNE"],
        ["Australia, Cairns [CNS]", "CNS"],
        ["Australia, Canberra [CBR]", "CBR"],
        ["Australia, Gold Coast [OOL]", "OOL"],
        ["Australia, Melbourne [MEB]", "MEB"],
        ["Australia, Newcastle [NTL]", "NTL"],
        ["Australia, Perth [JAD]", "JAD"],
        ["Australia, Sydney [BWU]", "BWU"],
        ["Austria, Vienna [VIE]", "VIE"],
        ["Azerbaijan, Baku [BAK]", "BAK"],
        ["Bahrain, Manama [BAH]", "BAH"],
        ["Bangladesh, Chittagong [CGP]", "CGP"],
        ["Bangladesh, Dhaka [DAC]", "DAC"],
        ["Barbados, Bridgetown [BGI]", "BGI"],
        ["Belarus, Minsk [MHP]", "MHP"],
        ["Belgium, Brussels [BRU]", "BRU"],
        ["Belize, Belize City [BZE]", "BZE"],
        ["Benin, Cotonou [COO]", "COO"],
        ["Benin, Porto-Novo [COO]", "COO"],
        ["Bhutan, Paro [PBH]", "PBH"],
        ["Bhutan, Thimphu [PBH]", "PBH"],
        ["Bolivia, La Paz [LPB]", "LPB"],
        ["Bolivia, Santa Cruz [VVI]", "VVI"],
        ["Bolivia, Sucre [SRE]", "SRE"],
        ["Bosnia and Herzegovina, Sarajevo [SJJ]", "SJJ"],
        ["Botswana, Gaborone [GBE]", "GBE"],
        ["Brazil, Belo Horizonte [PLU]", "PLU"],
        ["Brazil, Brasilia [BSB]", "BSB"],
        ["Brazil, Fortaleza [FOR]", "FOR"],
        ["Brazil, Porto Alegre [POA]", "POA"],
        ["Brazil, Recife [REC]", "REC"],
        ["Brazil, Rio de Janeiro [GIG]", "GIG"],
        ["Brazil, Salvador [SSA]", "SSA"],
        ["Brazil, Sao Paulo [GRU]", "GRU"],
        ["Brunei, Bandar Seri Begawan [BWN]", "BWN"],
        ["Bulgaria, Sofia [SOF]", "SOF"],
        ["Burkina Faso, Ouagadougou [OUA]", "OUA"],
        ["Burundi, Bujumbura [BJM]", "BJM"],
        ["Cambodia, Phnom Penh [PNH]", "PNH"],
        ["Cameroon, Douala [DLA]", "DLA"],
        ["Cameroon, Yaounde [YAO]", "YAO"],
        ["Canada, Calgary [YYC]", "YYC"],
        ["Canada, Montreal [YHU]", "YHU"],
        ["Canada, Ottawa [YOW]", "YOW"],
        ["Canada, Toronto [YKZ]", "YKZ"],
        ["Canada, Vancouver [YVR]", "YVR"],
        ["Cape Verde Islands, Praia [RAI]", "RAI"],
        ["Central African Republic, Bangui [BGF]", "BGF"],
        ["Chad, N'Djamena [NDJ]", "NDJ"],
        ["Chile, Santiago [SCL]", "SCL"],
        ["China, Beijing [PEK]", "PEK"],
        ["China, Chengdu [CTU]", "CTU"],
        ["China, Chongqing [CKG]", "CKG"],
        ["China, Guangzhou [CAN]", "CAN"],
        ["China, Guilin [KWL]", "KWL"],
        ["China, Hong Kong [HKG]", "HKG"],
        ["China, Kunming [KMG]", "KMG"],
        ["China, Lhasa [LXA]", "LXA"],
        ["China, Macau [MFM]", "MFM"],
        ["China, Nanjing [NKG]", "NKG"],
        ["China, Shanghai [SHA]", "SHA"],
        ["China, Taipei [TPE]", "TPE"],
        ["China, Tianjin [TSN]", "TSN"],
        ["China, Wuhan [WUH]", "WUH"],
        ["China, Xi'an [XIY]", "XIY"],
        ["Colombia, Bogota [BOG]", "BOG"],
        ["Colombia, Medellin [EOH]", "EOH"],
        ["Comoros Islands, Moroni [HAH]", "HAH"],
        ["Congo Democratic Republic of the, Kinshasa [FIH]", "FIH"],
        ["Congo Republic of the, Brazzaville [BZV]", "BZV"],
        ["Costa Rica, San Jose [SJO]", "SJO"],
        ["Croatia, Split [SPU]", "SPU"],
        ["Croatia, Zagreb [ZAG]", "ZAG"],
        ["Cuba, Havana [HAV]", "HAV"],
        ["Cyprus, Larnaca [LCA]", "LCA"],
        ["Cyprus, Paphos [PFO]", "PFO"],
        ["Czech Republic, Brno [BRQ]", "BRQ"],
        ["Czech Republic, Prague [PRG]", "PRG"],
        ["Denmark, Aarhus [AAR]", "AAR"],
        ["Denmark, Copenhagen [CPH]", "CPH"],
        ["Djibouti, Djibouti [JIB]", "JIB"],
        ["Dominica, Roseau [DOM]", "DOM"],
        ["Dominican Republic, Barahona [BRX]", "BRX"],
        ["Dominican Republic, Puerto Plata [POP]", "POP"],
        ["Dominican Republic, Santiago [STI]", "STI"],
        ["Dominican Republic, Santo Domingo [HEX]", "HEX"],
        ["East Timor, Dili [DIL]", "DIL"],
        ["Ecuador, Guayaquil [GYE]", "GYE"],
        ["Ecuador, Quito [UIO]", "UIO"],
        ["Egypt, Alexandria [ALY]", "ALY"],
        ["Egypt, Cairo [CAI]", "CAI"],
        ["Egypt, Luxor [LXR]", "LXR"],
        ["Egypt, Sharm El-Sheikh [SSH]", "SSH"],
        ["El Salvador, San Salvador [SAL]", "SAL"],
        ["Equatorial Guinea, Malabo [SSG]", "SSG"],
        ["Eritrea, Asmara [ASM]", "ASM"],
        ["Estonia, Tallinn [TLL]", "TLL"],
        ["Ethiopia, Addis Ababa [ADD]", "ADD"],
        ["Fiji, Suva [SUV]", "SUV"],
        ["Finland, Helsinki [HEM]", "HEM"],
        ["France, Ajaccio [AJA]", "AJA"],
        ["France, Biarritz [BIQ]", "BIQ"],
        ["France, Brest [BES]", "BES"],
        ["France, Lille [LIL]", "LIL"],
        ["France, Lyon [LYS]", "LYS"],
        ["France, Marseille [MRS]", "MRS"],
        ["France, Nantes [NTE]", "NTE"],
        ["France, Nice [NCE]", "NCE"],
        ["France, Paris [LBG]", "LBG"],
        ["France, Toulouse [TLS]", "TLS"],
        ["Gabon, Libreville [LBV]", "LBV"],
        ["Georgia, Tbilisi [TBS]", "TBS"],
        ["Germany, Berlin [SXF]", "SXF"],
        ["Germany, Cologne [CGN]", "CGN"],
        ["Germany, Frankfurt [FRA]", "FRA"],
        ["Germany, Hamburg [HAM]", "HAM"],
        ["Germany, Munich [MUC]", "MUC"],
        ["Ghana, Accra [ACC]", "ACC"],
        ["Greece, Athens [HEW]", "HEW"],
        ["Greece, Corfu [CFU]", "CFU"],
        ["Greece, Crete [HER]", "HER"],
        ["Greece, Kefalonia [EFL]", "EFL"],
        ["Greece, Kos [KGS]", "KGS"],
        ["Greece, Mykonos [JMK]", "JMK"],
        ["Greece, Rhodes [RHO]", "RHO"],
        ["Grenada, Saint George's [GND]", "GND"],
        ["Guam, Hagatna [GUM]", "GUM"],
        ["Guatemala, Guatemala City [GUA]", "GUA"],
        ["Guinea, Conakry [CKY]", "CKY"],
        ["Guinea-Bissau, Bissau [BXO]", "BXO"],
        ["Guyana, Georgetown [GEO]", "GEO"],
        ["Haiti, Port-au-Prince [PAP]", "PAP"],
        ["Honduras, Tegucigalpa [TGU]", "TGU"],
        ["Hungary, Budapest [BUD]", "BUD"],
        ["Iceland, Reykjavik [RKV]", "RKV"],
        ["India, Ahmedabad [AMD]", "AMD"],
        ["India, Bangalore [BLR]", "BLR"],
        ["India, Chennai [MAA]", "MAA"],
        ["India, Cochin [COK]", "COK"],
        ["India, Delhi [DEL]", "DEL"],
        ["India, Hyderabad [HYD]", "HYD"],
        ["India, Jaipur [JAI]", "JAI"],
        ["India, Kanpur [KNU]", "KNU"],
        ["India, Kolkata [CCU]", "CCU"],
        ["India, Lucknow [LKO]", "LKO"],
        ["India, Mumbai [BOM]", "BOM"],
        ["India, Nagpur [NAG]", "NAG"],
        ["India, Pune [PNQ]", "PNQ"],
        ["India, Surat [STV]", "STV"],
        ["India, Vadodara [BDQ]", "BDQ"],
        ["Indonesia, Bali [DPS]", "DPS"],
        ["Indonesia, Bandung [BDO]", "BDO"],
        ["Indonesia, Jakarta [CGK]", "CGK"],
        ["Iran, Teheran [THR]", "THR"],
        ["Iraq, Baghdad [SDA]", "SDA"],
        ["Ireland, Cork [ORK]", "ORK"],
        ["Ireland, Dublin [DUB]", "DUB"],
        ["Ireland, Shannon [SNN]", "SNN"],
        ["Israel, Eilat [ETH]", "ETH"],
        ["Israel, Jerusalem [JRS]", "JRS"],
        ["Israel, Tel Aviv [TLV]", "TLV"],
        ["Italy, Florence [FLR]", "FLR"],
        ["Italy, Genova [GOA]", "GOA"],
        ["Italy, Milan [LIN]", "LIN"],
        ["Italy, Naples [NAP]", "NAP"],
        ["Italy, Rome [CIA]", "CIA"],
        ["Italy, Sardinia (Alghero) [AHO]", "AHO"],
        ["Italy, Sardinia (Cagliari) [CAG]", "CAG"],
        ["Italy, Sardinia (Olbia) [OLB]", "OLB"],
        ["Italy, Sicily (Catania) [CTA]", "CTA"],
        ["Italy, Sicily (Palermo) [PMO]", "PMO"],
        ["Italy, Sicily (Trapani) [TPS]", "TPS"],
        ["Italy, Trieste [TRS]", "TRS"],
        ["Italy, Turin [TRN]", "TRN"],
        ["Italy, Venice [VCE]", "VCE"],
        ["Italy, Verona [VRN]", "VRN"],
        ["Ivory Coast, Abidjan [ABJ]", "ABJ"],
        ["Ivory Coast, Yamoussoukro [ASK]", "ASK"],
        ["Jamaica, Kingston [KIN]", "KIN"],
        ["Japan, Kobe [UKB]", "UKB"],
        ["Japan, Nagoya [NGO]", "NGO"],
        ["Japan, Osaka [ITM]", "ITM"],
        ["Japan, Tokyo [NRT]", "NRT"],
        ["Jordan, Amman [AMM]", "AMM"],
        ["Kazakhstan, Almaty [ALA]", "ALA"],
        ["Kazakhstan, Astana [TSE]", "TSE"],
        ["Kenya, Nairobi [NBO]", "NBO"],
        ["Kiribati, Tarawa Atoll [TRW]", "TRW"],
        ["Kuwait, Kuwait City [KWI]", "KWI"],
        ["Kyrgyzstan, Bishkek [FRU]", "FRU"],
        ["Laos, Vientiane [VTE]", "VTE"],
        ["Latvia, Riga [RIX]", "RIX"],
        ["Lebanon, Beirut [BEY]", "BEY"],
        ["Lesotho, Maseru [MSU]", "MSU"],
        ["Liberia, Monrovia [MLW]", "MLW"],
        ["Libya, Tripoli [TIP]", "TIP"],
        ["Lithuania, Vilnius [VNO]", "VNO"],
        ["Luxembourg, Luxembourg [LUX]", "LUX"],
        ["Macedonia, Skopje [SKP]", "SKP"],
        ["Madagascar, Antananarivo [TNR]", "TNR"],
        ["Malawi, Blantyre [BLZ]", "BLZ"],
        ["Malawi, Lilongwe [LLW]", "LLW"],
        ["Malaysia, Kuala Lumpur [KUL]", "KUL"],
        ["Malaysia, Penang [PEN]", "PEN"],
        ["Maldives, Male [MLE]", "MLE"],
        ["Mali, Bamako [BKO]", "BKO"],
        ["Malta, Valletta [MLA]", "MLA"],
        ["Marshall Islands, Majuro [MAJ]", "MAJ"],
        ["Mauritania, Nouakchott [NKC]", "NKC"],
        ["Mauritius, Plaisance [MRU]", "MRU"],
        ["Mauritius, Port Louis [MRU]", "MRU"],
        ["Mexico, Acapulco [ACA]", "ACA"],
        ["Mexico, Cancun [CUN]", "CUN"],
        ["Mexico, Cozumel [CZM]", "CZM"],
        ["Mexico, Guadalajara [GDL]", "GDL"],
        ["Mexico, La Paz [LAP]", "LAP"],
        ["Mexico, Merida [MID]", "MID"],
        ["Mexico, Mexico City [MEX]", "MEX"],
        ["Mexico, Monterrey [NTR]", "NTR"],
        ["Micronesia, Palikir [PNI]", "PNI"],
        ["Micronesia, Pohnpei [PNI]", "PNI"],
        ["Micronesia, Weno [TKK]", "TKK"],
        ["Moldova, Chisinau [KIV]", "KIV"],
        ["Monaco, Monaco [NCE]", "NCE"],
        ["Monaco, Monte Carlo [NCE]", "NCE"],
        ["Mongolia, Ulaanbaatar [ULN]", "ULN"],
        ["Montenegro, Podgorica [TGD]", "TGD"],
        ["Morocco, Casablanca [CAS]", "CAS"],
        ["Morocco, Marrakesh [RAK]", "RAK"],
        ["Morocco, Rabat [RBA]", "RBA"],
        ["Morocco, Tanger [TNG]", "TNG"],
        ["Mozambique, Maputo [MPM]", "MPM"],
        ["Myanmar (Burma), Naypyidaw [None]", "None"],
        ["Myanmar (Burma), Rangoon [RGN]", "RGN"],
        ["Namibia, Windhoek [WDH]", "WDH"],
        ["Nauru, Nauru Island [INU]", "INU"],
        ["Nepal, Kathmandu [KTM]", "KTM"],
        ["Netherlands, Amsterdam [AMS]", "AMS"],
        ["Netherlands, Maastricht [MST]", "MST"],
        ["Netherlands, Rotterdam [RTM]", "RTM"],
        ["New Zealand, Auckland [AKL]", "AKL"],
        ["New Zealand, Christchurch [CHC]", "CHC"],
        ["New Zealand, Wellington [WLG]", "WLG"],
        ["Nicaragua, Managua [MGA]", "MGA"],
        ["Niger, Niamey [NIM]", "NIM"],
        ["Nigeria, Abuja [ABV]", "ABV"],
        ["Nigeria, Ibadan [IBA]", "IBA"],
        ["Nigeria, Ilorin [ILR]", "ILR"],
        ["Nigeria, Kano [KAN]", "KAN"],
        ["Nigeria, Lagos [LOS]", "LOS"],
        ["Nigeria, Port Harcourt [PHC]", "PHC"],
        ["Norfolk Island, Burnt Pine [NLK]", "NLK"],
        ["North Korea, Pyongyang [FNJ]", "FNJ"],
        ["Norway, Bergen [BGO]", "BGO"],
        ["Norway, Oslo [FBU]", "FBU"],
        ["Oman, Muscat [MCT]", "MCT"],
        ["Pakistan, Faisalabad [LYP]", "LYP"],
        ["Pakistan, Gujranwala [SKT]", "SKT"],
        ["Pakistan, Islamabad [ISB]", "ISB"],
        ["Pakistan, Karachi [KHI]", "KHI"],
        ["Pakistan, Lahore [LHE]", "LHE"],
        ["Pakistan, Multan [MUX]", "MUX"],
        ["Pakistan, Peshawar [PEW]", "PEW"],
        ["Pakistan, Quetta [UET]", "UET"],
        ["Palau, Melekeok [ROR]", "ROR"],
        ["Panama, Panama City [PTY]", "PTY"],
        ["Papua New Guinea, Port Moresby [POM]", "POM"],
        ["Paraguay, Asuncion [ASU]", "ASU"],
        ["Peru, Lima [LIM]", "LIM"],
        ["Philippines, Manila [MNL]", "MNL"],
        ["Poland, Gdansk [GDN]", "GDN"],
        ["Poland, Krakow [KRK]", "KRK"],
        ["Poland, Szczechin [SZZ]", "SZZ"],
        ["Poland, Warsaw [WAW]", "WAW"],
        ["Poland, Wroclaw [WRO]", "WRO"],
        ["Portugal, Funchal (Madeira) [FNC]", "FNC"],
        ["Portugal, Lisbon [LIS]", "LIS"],
        ["Portugal, Porto [OPO]", "OPO"],
        ["Puerto Rico, San Juan [SIG]", "SIG"],
        ["Qatar, Doha [DOH]", "DOH"],
        ["Romania, Bucharest [BBU]", "BBU"],
        ["Russia, Krasnodar [KRR]", "KRR"],
        ["Russia, Moscow [SVO]", "SVO"],
        ["Russia, Saint Petersburg [LED]", "LED"],
        ["Russia, Samara [KBY]", "KBY"],
        ["Rwanda, Kigali [KGL]", "KGL"],
        ["Saint Kitts and Nevis, Basse Terre [SKB]", "SKB"],
        ["Saint Lucia, Castries [SLU]", "SLU"],
        ["Saint Vincent and the Grenadines, Kingstown [SVD]", "SVD"],
        ["Samoa, Apia [APW]", "APW"],
        ["Sao Tome and Principe, Sao Tome [TMS]", "TMS"],
        ["Saudi Arabia, Jeddah [JED]", "JED"],
        ["Saudi Arabia, Riyadh [RUH]", "RUH"],
        ["Senegal, Dakar [DKR]", "DKR"],
        ["Serbia, Belgrade [BEG]", "BEG"],
        ["Seychelles, Victoria [SEZ]", "SEZ"],
        ["Sierra Leone, Freetown [FNA]", "FNA"],
        ["Singapore, Singapore [XSP]", "XSP"],
        ["Slovakia, Bratislava [BTS]", "BTS"],
        ["Slovenia, Ljubljana [LJU]", "LJU"],
        ["Solomon Islands, Honiara [HIR]", "HIR"],
        ["Somalia, Mogadishu [MGQ]", "MGQ"],
        ["South Africa, Bloemfontein [BFN]", "BFN"],
        ["South Africa, Cape Town [CPT]", "CPT"],
        ["South Africa, Johannesburg [GCJ]", "GCJ"],
        ["South Africa, Pretoria [PRY]", "PRY"],
        ["South Korea, Busan [PUS]", "PUS"],
        ["South Korea, Seoul [ICN]", "ICN"],
        ["Spain, Alicante [ALC]", "ALC"],
        ["Spain, Almeria [LEI]", "LEI"],
        ["Spain, Asturias [OVD]", "OVD"],
        ["Spain, Barcelona [BCN]", "BCN"],
        ["Spain, Fuerteventura [FUE]", "FUE"],
        ["Spain, Gran Canaria [LPA]", "LPA"],
        ["Spain, Ibiza [IBZ]", "IBZ"],
        ["Spain, Lanzarote [ACE]", "ACE"],
        ["Spain, Madrid [MAD]", "MAD"],
        ["Spain, Malaga [AGP]", "AGP"],
        ["Spain, Mallorca [PMI]", "PMI"],
        ["Spain, Menorca [MAH]", "MAH"],
        ["Spain, Santander [SDR]", "SDR"],
        ["Spain, Seville [SVQ]", "SVQ"],
        ["Spain, Tenerife [TFS]", "TFS"],
        ["Spain, Valencia [VLC]", "VLC"],
        ["Sri Lanka, Colombo [CMB]", "CMB"],
        ["Sudan, Khartoum [KRT]", "KRT"],
        ["Sudan, Omdurman [KRT]", "KRT"],
        ["Suriname, Paramaribo [ORG]", "ORG"],
        ["Swaziland, Manzini [MTS]", "MTS"],
        ["Swaziland, Mbabane [MTS]", "MTS"],
        ["Sweden, Gothenburg [GOT]", "GOT"],
        ["Sweden, Stockholm [NYO]", "NYO"],
        ["Switzerland, Basel [BSL]", "BSL"],
        ["Switzerland, Bern [BRN]", "BRN"],
        ["Switzerland, Geneva [GVA]", "GVA"],
        ["Switzerland, Zurich [ZRH]", "ZRH"],
        ["Syria, Damascus [DAM]", "DAM"],
        ["Taiwan, Taipei [TPE]", "TPE"],
        ["Tajikistan, Dushanbe [DYU]", "DYU"],
        ["Tanzania, Dar es Salaam [DAR]", "DAR"],
        ["Tanzania, Dodoma [DOD]", "DOD"],
        ["Thailand, Bangkok [BKK]", "BKK"],
        ["Thailand, Phuket [HKT]", "HKT"],
        ["The Bahamas, Nassau [NAS]", "NAS"],
        ["The Gambia, Banjul [BJL]", "BJL"],
        ["Togo, Lome [LFW]", "LFW"],
        ["Tonga, Nuku'alofa [TBU]", "TBU"],
        ["Trinidad and Tobago, Port-of-Spain [POS]", "POS"],
        ["Tunisia, Tunis [TUN]", "TUN"],
        ["Turkey, Ankara [ESB]", "ESB"],
        ["Turkey, Dalaman [DLM]", "DLM"],
        ["Turkey, Istanbul [IST]", "IST"],
        ["Turkmenistan, Ashgabat [ASB]", "ASB"],
        ["Tuvalu, Vaiaku village [FUN]", "FUN"],
        ["Uganda, Kampala [EBB]", "EBB"],
        ["Ukraine, Dnepropetrovsk [DNK]", "DNK"],
        ["Ukraine, Kharkov [HRK]", "HRK"],
        ["Ukraine, Kiev [KBP]", "KBP"],
        ["United Arab Emirates, Abu Dhabi [AUH]", "AUH"],
        ["United Arab Emirates, Dubai [DXB]", "DXB"],
        ["United Arab Emirates, Sharjah [SHJ]", "SHJ"],
        ["United States, Albany [ALB]", "ALB"],
        ["United States, Annapolis [BWI]", "BWI"],
        ["United States, Atlanta [ATL]", "ATL"],
        ["United States, Augusta [AUG]", "AUG"],
        ["United States, Austin [AUS]", "AUS"],
        ["United States, Baltimore [BWI]", "BWI"],
        ["United States, Baton Rouge [BTR]", "BTR"],
        ["United States, Bismarck [BIS]", "BIS"],
        ["United States, Boise [BOI]", "BOI"],
        ["United States, Boston [BOS]", "BOS"],
        ["United States, Carson City [CSN]", "CSN"],
        ["United States, Charleston [CHS]", "CHS"],
        ["United States, Charlotte [CLT]", "CLT"],
        ["United States, Cheyenne [CYS]", "CYS"],
        ["United States, Chicago [MDW]", "MDW"],
        ["United States, Cleveland [CLE]", "CLE"],
        ["United States, Colorado Springs [COS]", "COS"],
        ["United States, Columbia [COU]", "COU"],
        ["United States, Columbus [CMH]", "CMH"],
        ["United States, Concord [MHT]", "MHT"],
        ["United States, Dallas [DAL]", "DAL"],
        ["United States, Denver [DEN]", "DEN"],
        ["United States, Des Moines [DSM]", "DSM"],
        ["United States, Detroit [DET]", "DET"],
        ["United States, Dover [DOV]", "DOV"],
        ["United States, El Paso [BIF]", "BIF"],
        ["United States, Fort Worth [FTW]", "FTW"],
        ["United States, Frankfort [SDF]", "SDF"],
        ["United States, Harrisburg [HAR]", "HAR"],
        ["United States, Hartford [HFD]", "HFD"],
        ["United States, Helena [HLN]", "HLN"],
        ["United States, Honolulu [HNL]", "HNL"],
        ["United States, Houston [EFD]", "EFD"],
        ["United States, Indianapolis [IND]", "IND"],
        ["United States, Jackson [JAN]", "JAN"],
        ["United States, Jefferson City [JEF]", "JEF"],
        ["United States, Juneau [JNU]", "JNU"],
        ["United States, Kansas City [MCI]", "MCI"],
        ["United States, Lansing [LAN]", "LAN"],
        ["United States, Las Vegas [LAS]", "LAS"],
        ["United States, Lincoln [LNK]", "LNK"],
        ["United States, Little Rock [LIT]", "LIT"],
        ["United States, Los Angeles [LAX]", "LAX"],
        ["United States, Louisville [SDF]", "SDF"],
        ["United States, Madison [MSN]", "MSN"],
        ["United States, Memphis [MEM]", "MEM"],
        ["United States, Miami [MIA]", "MIA"],
        ["United States, Milwaukee [MKE]", "MKE"],
        ["United States, Minneapolis [MSP]", "MSP"],
        ["United States, Montgomery [MXF]", "MXF"],
        ["United States, Montpelier [MPV]", "MPV"],
        ["United States, Nashville [BNA]", "BNA"],
        ["United States, New Orleans [MSY]", "MSY"],
        ["United States, New York City [JFK]", "JFK"],
        ["United States, Newark [EWR]", "EWR"],
        ["United States, Oakland [OAK]", "OAK"],
        ["United States, Oklahoma City [OKC]", "OKC"],
        ["United States, Olympia [OLM]", "OLM"],
        ["United States, Orlando [MCO]", "MCO"],
        ["United States, Philadelphia [PHL]", "PHL"],
        ["United States, Phoenix [LUF]", "LUF"],
        ["United States, Pierre [PIR]", "PIR"],
        ["United States, Portland [PDX]", "PDX"],
        ["United States, Providence [PVD]", "PVD"],
        ["United States, Raleigh [RDU]", "RDU"],
        ["United States, Richmond [RIC]", "RIC"],
        ["United States, Sacramento [MCC]", "MCC"],
        ["United States, Saint Paul [MSP]", "MSP"],
        ["United States, Salem [SLE]", "SLE"],
        ["United States, Salt Lake City [SLC]", "SLC"],
        ["United States, San Antonio [RND]", "RND"],
        ["United States, San Diego [NZY]", "NZY"],
        ["United States, San Francisco [SFO]", "SFO"],
        ["United States, Santa Fe [SAF]", "SAF"],
        ["United States, Seattle [BFI]", "BFI"],
        ["United States, Springfield [SPI]", "SPI"],
        ["United States, Tallahassee [TLH]", "TLH"],
        ["United States, Topeka [FOE]", "FOE"],
        ["United States, Trenton [TTN]", "TTN"],
        ["United States, Washington D.C. [IAD]", "IAD"],
        ["Uruguay, Montevideo [MVD]", "MVD"],
        ["Uzbekistan, Tashkent [TAS]", "TAS"],
        ["Vanuatu, Port-Vila [VLI]", "VLI"],
        ["Venezuela, Caracas [CCS]", "CCS"],
        ["Vietnam, Hanoi [HAN]", "HAN"],
        ["Vietnam, Ho Chi Minh City [SGN]", "SGN"],
        ["Yemen, Sanaa [SAH]", "SAH"],
        ["Zambia, Lusaka [LUN]", "LUN"],
        ["Zimbabwe, Harare [HRE]", "HRE"],
      ]
    end

  end

end
